name: Deploy Hypervel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Push (opsional)
        run: docker compose -f docker-compose.yml up -d --build

      - name: Run Artisan Migrate
        run: docker exec hypervel-app php artisan migrate --force
      
      - name: Build Docker Images
        run: docker compose -f docker-compose.yml build

      - name: Start Services
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for app to be ready
        run: sleep 10

      - name: Run Artisan Migrate
        run: docker exec hypervel-app php artisan migrate --force

